// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Mutation struct {
}

type NewProduct struct {
	ID string `json:"ID"`
}

type Query struct {
}

type Product struct {
	ID string `json:"id"`
}
